from sqlalchemy import create_engine, Table, MetaData, Column, ForeignKey, INTEGER, TEXT, REAL, BOOLEAN, TypeDecorator

class PaddedInt(TypeDecorator):
    impl = INTEGER

    def __init__(self, digits):
        super().__init__()
        self.digits = digits

    def process_result_value(self, value, dialect):
        return u'{0:0{1}d}'.format(value or 0, self.digits)

metadata =  MetaData(create_engine('sqlite:///library.blb'))


album_attributes = Table('album_attributes', metadata,
    Column('id', INTEGER(), primary_key=True, nullable=False),
    Column('entity_id', INTEGER()),
    Column('key', TEXT()),
    Column('value', TEXT()),
)
album_genre = Table('album_genre', metadata,
    Column('album_id', INTEGER()),
    Column('genre_id', ForeignKey('album.id')),
)
albums = Table('albums', metadata,
    Column('id', INTEGER(), primary_key=True, nullable=False),
    Column('artpath', TEXT()),
    Column('added', REAL()),
    Column('albumartist', TEXT()),
    Column('albumartist_sort', TEXT()),
    Column('albumartist_credit', TEXT()),
    Column('album', TEXT()),
    Column('genre', TEXT()),
    Column('style', TEXT()),
    Column('discogs_albumid', INTEGER()),
    Column('discogs_artistid', INTEGER()),
    Column('discogs_labelid', INTEGER()),
    Column('year', INTEGER()),
    Column('month', INTEGER()),
    Column('day', INTEGER()),
    Column('disctotal', INTEGER()),
    Column('comp', INTEGER()),
    Column('mb_albumid', TEXT()),
    Column('mb_albumartistid', TEXT()),
    Column('albumtype', TEXT()),
    Column('label', TEXT()),
    Column('mb_releasegroupid', TEXT()),
    Column('asin', TEXT()),
    Column('catalognum', TEXT()),
    Column('script', TEXT()),
    Column('language', TEXT()),
    Column('country', TEXT()),
    Column('albumstatus', TEXT()),
    Column('albumdisambig', TEXT()),
    Column('releasegroupdisambig', TEXT()),
    Column('rg_album_gain', REAL()),
    Column('rg_album_peak', REAL()),
    Column('r128_album_gain', INTEGER()),
    Column('original_year', INTEGER()),
    Column('original_month', INTEGER()),
    Column('original_day', INTEGER()),
)
genres = Table('genres', metadata,
    Column('id', INTEGER(), primary_key=True, nullable=False),
    Column('genre', TEXT()),
)
item_attributes = Table('item_attributes', metadata,
    Column('id', INTEGER(), primary_key=True, nullable=False),
    Column('entity_id', INTEGER()),
    Column('key', TEXT()),
    Column('value', TEXT()),
)

item_genre = Table('item_genre', metadata,
    Column('album_id', ForeignKey('album.id')),
    Column('genre_id', ForeignKey('genre.id')),
    Column('item_id', ForeignKey('item.id')),
)
items = Table('items', metadata,
    Column('id', INTEGER(), primary_key=True, nullable=False),
    Column('path', TEXT()),
    Column('album_id', ForeignKey('item.id')),
    Column('title', TEXT()),
    Column('artist', TEXT()),
    Column('artist_sort', TEXT()),
    Column('artist_credit', TEXT()),
    Column('album', TEXT()),
    Column('albumartist', TEXT()),
    Column('albumartist_sort', TEXT()),
    Column('albumartist_credit', TEXT()),
    Column('genre', TEXT()),
    Column('style', TEXT()),
    Column('discogs_albumid', INTEGER()),
    Column('discogs_artistid', INTEGER()),
    Column('discogs_labelid', INTEGER()),
    Column('lyricist', TEXT()),
    Column('composer', TEXT()),
    Column('composer_sort', TEXT()),
    Column('work', TEXT()),
    Column('mb_workid', TEXT()),
    Column('work_disambig', TEXT()),
    Column('arranger', TEXT()),
    Column('grouping', TEXT()),
    Column('year', PaddedInt(4)),
    Column('month', PaddedInt(2)),
    Column('day', PaddedInt(2)),
    Column('track', PaddedInt(2)),
    Column('tracktotal', PaddedInt(2)),
    Column('disc', PaddedInt(2)),
    Column('disctotal', PaddedInt(2)),
    Column('lyrics', TEXT()),
    Column('comments', TEXT()),
    Column('bpm', INTEGER()),
    Column('comp', BOOLEAN),
    Column('mb_trackid', TEXT()),
    Column('mb_albumid', TEXT()),
    Column('mb_artistid', TEXT()),
    Column('mb_albumartistid', TEXT()),
    Column('mb_releasetrackid', TEXT()),
    Column('albumtype', TEXT()),
    Column('label', TEXT()),
    Column('acoustid_fingerprint', TEXT()),
    Column('acoustid_id', TEXT()),
    Column('mb_releasegroupid', TEXT()),
    Column('asin', TEXT()),
    Column('catalognum', TEXT()),
    Column('script', TEXT()),
    Column('language', TEXT()),
    Column('country', TEXT()),
    Column('albumstatus', TEXT()),
    Column('media', TEXT()),
    Column('albumdisambig', TEXT()),
    Column('releasegroupdisambig', TEXT()),
    Column('disctitle', TEXT()),
    Column('encoder', TEXT()),
    Column('rg_track_gain', REAL()),
    Column('rg_track_peak', REAL()),
    Column('rg_album_gain', REAL()),
    Column('rg_album_peak', REAL()),
    Column('r128_track_gain', INTEGER()),
    Column('r128_album_gain', INTEGER()),
    Column('original_year', INTEGER()),
    Column('original_month', INTEGER()),
    Column('original_day', INTEGER()),
    Column('initial_key', TEXT()),
    Column('length', REAL()),
    Column('bitrate', INTEGER()),
    Column('format', TEXT()),
    Column('samplerate', INTEGER()),
    Column('bitdepth', INTEGER()),
    Column('channels', INTEGER()),
    Column('mtime', REAL()),
    Column('added', REAL()),
)
